print('Задача 6. Проверяем бухгалтера')
first_number = int(input('Введите первое число: '))
second_number = int(input('Введите второе число: '))
result = (first_number % 100) + (second_number % 100)
print('Сумма: ', result)